Collecting geopandas
  Using cached geopandas-0.9.0-py2.py3-none-any.whl (994 kB)
Requirement already satisfied: pandas>=0.24.0 in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from geopandas) (1.2.3)
Requirement already satisfied: shapely>=1.6 in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from geopandas) (1.7.1)
Requirement already satisfied: pyproj>=2.2.0 in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from geopandas) (3.0.1)
Collecting fiona>=1.8
  Using cached Fiona-1.8.19.tar.gz (1.3 MB)
  Using cached Fiona-1.8.18.tar.gz (1.3 MB)
  Using cached Fiona-1.8.17.tar.gz (1.3 MB)
  Using cached Fiona-1.8.16.tar.gz (1.3 MB)
  Using cached Fiona-1.8.15.tar.gz (1.3 MB)
  Using cached Fiona-1.8.14.tar.gz (1.3 MB)
  Using cached Fiona-1.8.13.post1.tar.gz (1.2 MB)
  Using cached Fiona-1.8.13.tar.gz (1.2 MB)
  Using cached Fiona-1.8.12.tar.gz (1.2 MB)
  Using cached Fiona-1.8.11.tar.gz (1.2 MB)
  Using cached Fiona-1.8.10.tar.gz (1.2 MB)
  Using cached Fiona-1.8.9.post2.tar.gz (1.2 MB)
  Using cached Fiona-1.8.9.post1.tar.gz (1.2 MB)
  Using cached Fiona-1.8.9.tar.gz (1.2 MB)
  Using cached Fiona-1.8.8.tar.gz (1.7 MB)
  Using cached Fiona-1.8.7.tar.gz (1.7 MB)
  Using cached Fiona-1.8.6.tar.gz (1.7 MB)
  Using cached Fiona-1.8.5.tar.gz (1.7 MB)
  Using cached Fiona-1.8.4.tar.gz (1.1 MB)
  Using cached Fiona-1.8.3.tar.gz (1.1 MB)
  Using cached Fiona-1.8.2.tar.gz (1.2 MB)
  Using cached Fiona-1.8.1.tar.gz (1.1 MB)
  Using cached Fiona-1.8.0.tar.gz (1.4 MB)
Collecting geopandas
  Using cached geopandas-0.8.2-py2.py3-none-any.whl (962 kB)
Collecting fiona
  Using cached Fiona-1.7.13.tar.gz (731 kB)
Requirement already satisfied: numpy>=1.16.5 in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from pandas>=0.24.0->geopandas) (1.20.2)
Requirement already satisfied: pytz>=2017.3 in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from pandas>=0.24.0->geopandas) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from pandas>=0.24.0->geopandas) (2.8.1)
Requirement already satisfied: certifi in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from pyproj>=2.2.0->geopandas) (2020.12.5)
Requirement already satisfied: six>=1.5 in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->geopandas) (1.15.0)
Requirement already satisfied: cligj>=0.4 in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from fiona->geopandas) (0.7.1)
Requirement already satisfied: click-plugins in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from fiona->geopandas) (1.1.1)
Requirement already satisfied: munch in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from fiona->geopandas) (2.5.0)
Requirement already satisfied: click<8,>=4.0 in d:\jupyter_notebooks\python_data_analysis_2021\venv\lib\site-packages (from cligj>=0.4->fiona->geopandas) (7.1.2)
Using legacy 'setup.py install' for fiona, since package 'wheel' is not installed.
Installing collected packages: fiona, geopandas
    Running setup.py install for fiona: started
    Running setup.py install for fiona: finished with status 'error'
